# config.yaml
# 统一配置 RMSD、Rename、MSA/Index Mapping、GD/AF3 PPI、Overlap 参数

common:
  N_JOBS: 4
  plot_bins: 50
  plot_kde: true
  scheme: "kabat"
  similarity_threshold: 0.9
  ncpu: 1
  ANTIGEN_CHAIN: "A"
  CHAIN_TARGET: "A"
  CHAIN_QUERY: "H,L"
  NO_PYMOL: true
  OVERLAP_THRESHOLD: 0.6


rmsd:
  GROUND_TRUTH_PATH: "/home/yuyang/lb_yaml/data/PD1/6jjp.pdb"
  PREDICTED_DIR: "/home/yuyang/lb_yaml/data/PD1/cif"
  OUTPUT_DIR: "/home/yuyang/lb_yaml/data/PD1/output"

rename:
  PDB_NAME: "6jjp.pdb"
  PDB_DIR: "/home/yuyang/lb_yaml/data/PD1"
  CIF_DIR: "/home/yuyang/lb_yaml/data/PD1/cif"

msa_index_map:
  PDB_FILE: "/home/yuyang/lb_yaml/data/PD1/6jjp.pdb"
  CIF_DIR: "/home/yuyang/lb_yaml/data/PD1/cif"
  OUTPUT_FASTA: "/home/yuyang/lb_yaml/data/PD1/msa_fasta/PD1_antigen_for_msa.fasta"
  OUTPUT_ALN: "/home/yuyang/lb_yaml/data/PD1/msa_aln/PD1_antigen_for_msa.aln.fasta"
  OUTPUT_MAPPING: "/home/yuyang/lb_yaml/data/PD1/pdb_to_af3_mapping.csv"

gd_results_ppi:
  PDB_FILE: "/home/yuyang/lb_yaml/data/PD1/6jjp.pdb"
  PPI_DIR: "/home/yuyang/lb_yaml/data/PD1/ppi_csv_gd"
  OUTPUT_SUMMARY: "/home/yuyang/lb_yaml/data/PD1/ppi_summary_gd.csv"

af3_results_ppi:
  CIF_FOLDER: "/home/yuyang/lb_yaml/data/PD1/cif"
  PDB_FOLDER: "/home/yuyang/lb_yaml/data/PD1/cif_pdb"
  RMSD_FILE: "/home/yuyang/lb_yaml/data/PD1/output/VHVL_RMSD_results.csv"
  PPI_FOLDER: "/home/yuyang/lb_yaml/data/PD1/ppi_csv_af3"
  PPI_SUMMARY: "/home/yuyang/lb_yaml/data/PD1/ppi_summary_af3.csv"
  MAPPING_FILE: "/home/yuyang/lb_yaml/data/PD1/pdb_to_af3_mapping.csv"
  OUTPUT_MAPPING: "/home/yuyang/lb_yaml/data/PD1/ppi_summary_mapping.csv"

overlap:
  AF3_FILE: "/home/yuyang/lb_yaml/data/PD1/ppi_summary_af3.csv"
  GD_FILE: "/home/yuyang/lb_yaml/data/PD1/ppi_summary_gd.csv"
  MAP_FILE: "/home/yuyang/lb_yaml/data/PD1/pdb_to_af3_mapping.csv"
  OUTPUT_FILE_SIMPLE: "/home/yuyang/lb_yaml/data/PD1/af3_gd_overlap.csv"
  OUTPUT_FILE_MAPPED: "/home/yuyang/lb_yaml/data/PD1/af3_gd_overlap_mapped.csv"
  THRESHOLD: 0.6
